import type { NextPage } from 'next'
import Head from 'next/head'

import Basic from 'components/Basic'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Slate + Next.ts</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='container min-h-screen p-8 mx-auto bg-gray-200'>
        <h1 className='text-5xl text-center text-gray-600'>
          Slate +<span className='text-blue-600'>Next.ts!</span>
        </h1>

        {/* start here... */}
        <Basic />
      </main>
    </div>
  )
}

export default Home
