import type { NextPage } from 'next'
import Head from 'next/head'

import BasicRTE from 'components/BasicRTE'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Slate + Next.ts</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='container min-h-screen p-8 mx-auto bg-gray-200'>
        <h1 className='text-5xl text-center text-gray-600'>
          Slate +<span className='text-blue-600'>Next.ts!</span>
        </h1>

        {/* start here... */}
        <section className='max-w-xl px-8 pt-4 pb-6 mx-auto mt-10 border-2 border-blue-500 rounded-md'>
          <h2 className='mb-8 text-3xl font-semibold text-center text-gray-500'>
            Basic RTE
          </h2>
          <BasicRTE />
        </section>
      </main>
    </div>
  )
}

export default Home
